### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by rafaeltiveron** [jaredsampson/pymolprobity#11]
How to cite PyMOLProbity?

**Comment by jaredsampson** [comment]
@rafaeltiveron Thanks for asking. I hadn't really considered this previously, but just saw that GitHub has established a [method](https://guides.github.com/activities/citable-code/) for creating DOIs for specific releases of the software through Zenodo.  I'll put together citation instructions and create a new release, which should then produce a citable DOI for all future releases.

**Comment by jaredsampson** [comment]
I have added citation info to [README.md](https://github.com/jaredsampson/pymolprobity/blob/master/README.md#citing-pymolprobity).  I also set up the Zenodo DOI webhook, so a new DOI is generated for each release.  Hopefully that's enough for you to move forward, so I'll close the issue.  If there's anything else you need, please let me know.

**Comment by rafaeltiveron** [comment]
Thank you
